# lowercase letters required therefore 'eml'
app = "mediator-##meter-serial##"
primary_region = "lhr"

[build]
  # never deployed, just need some image when we "fly launch --no-deploy ..."
  # to create the app from this toml file.
  image = 'hello-world'

[[services]]
  protocol = "tcp"
  internal_port = 50051
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 50051  # External port clients will connect to
    handlers = []  # Empty handlers = pure TCP passthrough

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
