app = 'mediator-mgf-eml2424295755'
primary_region = 'lhr'

[build]
  image = 'hello-world'

[[services]]
  protocol = 'tcp'
  internal_port = 50051
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 50051

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
