# fly.toml app configuration file generated for mediator-mgf-eml2424295768 on 2025-12-08T11:43:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mediator-mgf-eml2424295768'
primary_region = 'lhr'

[build]
  image = 'hello-world'

[[services]]
  protocol = 'tcp'
  internal_port = 50051
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 50051

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
